/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.ilu4.jeuxpirate.boundary;

import com.ilu4.jeuxpirate.boundary.components.Point_de_vie;
import com.ilu4.jeuxpirate.boundary.componentManager.GestionnaireCartes;
import com.ilu4.jeuxpirate.boundary.components.JCarte;
import com.ilu4.jeuxpirate.boundary.components.Zone_d_interaction;
import com.ilu4.jeuxpirate.boundary.components.ImagePanel;
import java.awt.Component;
import java.awt.Rectangle;
import java.io.IOException;

public class Plateau extends javax.swing.JPanel {

    private Zone_d_interaction zoneInteraction = null;
    private JCarte carte ;
    private GestionnaireCartes gestionnaire = new GestionnaireCartes();
    /**
     * Creates new form Plateau
     */
    public Plateau() {
        initComponents();
        zoneInteraction = zone_d_interaction1;
        carte = jCarte1;
        jCarte1.changeCardFace();
        gestionnaire.ajouterCarte(carte);
        carte = jCarte2;
        gestionnaire.ajouterCarte(carte);
        gestionnaire.ajouterCarte(carte);
        gestionnaire.ajouterZone(zone_d_interaction1);
        setNbViesRestantes(4);
        //imageJ1.setImage("com/ilu4/jeuxpirate/boundary/ressources/Icon12.png");
        //imageJ2.setImage("com/ilu4/jeuxpirate/boundary/ressources/Icon12.png");
        //PopJ1.setImage("com/ilu4/jeuxpirate/boundary/ressources/Icon12.png");
        //PopJ2.setImage("com/ilu4/jeuxpirate/boundary/ressources/Icon12.png");
        //imagePanel1.setImage("/com.ilu4.jeuxpirate.boundary.ressources/blackSmoke00.png");
        // VOIR POURQUOI IL MET UNE IMAGE COMME ... JE SAIS PAS
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   
    //Je comprends pas pourquoi ça comprend pas ce truc
    public GestionnaireCartes getGestionnaire() {
        return gestionnaire;
    }
   
    public void verifierZoneInteraction(Rectangle boundsCarte) {
	zone_d_interaction1.verifierCarte(carte);
        Rectangle boundsZone = zoneInteraction.getBounds();
        if (boundsZone.intersects(boundsCarte)) {
            //JOptionPane.showMessageDialog(this, "Carte déposée dans la zone !");    // debuggage
        }
    }
    public void setNbViesRestantes(int n) {
        Component[] composants = JaugePoint_de_vie.getComponents();
        for (int i = 0; i < composants.length; i++) {
            if (composants[i] instanceof Point_de_vie coeur) {
                coeur.setEtat(i < n); // les premiers pleins, le reste vides
            }
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageJ1 = new com.ilu4.jeuxpirate.boundary.components.ImagePanel();
        zone_d_interaction1 = new com.ilu4.jeuxpirate.boundary.components.Zone_d_interaction();
        jCarte2 = new com.ilu4.jeuxpirate.boundary.components.JCarte();
        jCarte1 = new com.ilu4.jeuxpirate.boundary.components.JCarte();
        JaugePoint_de_vie = new javax.swing.JPanel();
        point_de_vie1 = new com.ilu4.jeuxpirate.boundary.components.Point_de_vie();
        point_de_vie2 = new com.ilu4.jeuxpirate.boundary.components.Point_de_vie();
        point_de_vie4 = new com.ilu4.jeuxpirate.boundary.components.Point_de_vie();
        point_de_vie6 = new com.ilu4.jeuxpirate.boundary.components.Point_de_vie();
        point_de_vie10 = new com.ilu4.jeuxpirate.boundary.components.Point_de_vie();
        zone_d_interaction2 = new com.ilu4.jeuxpirate.boundary.components.Zone_d_interaction();
        PopJ2 = new com.ilu4.jeuxpirate.boundary.components.ImagePanel();
        imageJ2 = new com.ilu4.jeuxpirate.boundary.components.ImagePanel();
        zone_d_interaction3 = new com.ilu4.jeuxpirate.boundary.components.Zone_d_interaction();
        zone_d_interaction5 = new com.ilu4.jeuxpirate.boundary.components.Zone_d_interaction();
        zone_d_interaction6 = new com.ilu4.jeuxpirate.boundary.components.Zone_d_interaction();
        zone_d_interaction7 = new com.ilu4.jeuxpirate.boundary.components.Zone_d_interaction();
        zone_d_interaction8 = new com.ilu4.jeuxpirate.boundary.components.Zone_d_interaction();
        JaugePoint_de_vie1 = new javax.swing.JPanel();
        point_de_vie3 = new com.ilu4.jeuxpirate.boundary.components.Point_de_vie();
        point_de_vie5 = new com.ilu4.jeuxpirate.boundary.components.Point_de_vie();
        point_de_vie7 = new com.ilu4.jeuxpirate.boundary.components.Point_de_vie();
        point_de_vie8 = new com.ilu4.jeuxpirate.boundary.components.Point_de_vie();
        point_de_vie11 = new com.ilu4.jeuxpirate.boundary.components.Point_de_vie();
        PopJ1 = new com.ilu4.jeuxpirate.boundary.components.ImagePanel();
        zone_d_interaction4 = new com.ilu4.jeuxpirate.boundary.components.Zone_d_interaction();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imageJ1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout imageJ1Layout = new javax.swing.GroupLayout(imageJ1);
        imageJ1.setLayout(imageJ1Layout);
        imageJ1Layout.setHorizontalGroup(
            imageJ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
        );
        imageJ1Layout.setVerticalGroup(
            imageJ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );

        add(imageJ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 330, 130, 150));

        zone_d_interaction1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        try{
            jCarte2.setImage("Card1FrontAttack.png");
        } catch (IOException e){
            System.out.print("Card not found");
        }

        javax.swing.GroupLayout jCarte2Layout = new javax.swing.GroupLayout(jCarte2);
        jCarte2.setLayout(jCarte2Layout);
        jCarte2Layout.setHorizontalGroup(
            jCarte2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );
        jCarte2Layout.setVerticalGroup(
            jCarte2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
        );

        zone_d_interaction1.add(jCarte2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 90, 130));

        jCarte1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try{
            jCarte1.setImage("Card1FrontAttack.png");
        } catch (IOException e){
            System.out.print("Card not found");
        }

        javax.swing.GroupLayout jCarte1Layout = new javax.swing.GroupLayout(jCarte1);
        jCarte1.setLayout(jCarte1Layout);
        jCarte1Layout.setHorizontalGroup(
            jCarte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );
        jCarte1Layout.setVerticalGroup(
            jCarte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
        );

        zone_d_interaction1.add(jCarte1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, 130));

        add(zone_d_interaction1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 460, 150));

        JaugePoint_de_vie.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout point_de_vie1Layout = new javax.swing.GroupLayout(point_de_vie1);
        point_de_vie1.setLayout(point_de_vie1Layout);
        point_de_vie1Layout.setHorizontalGroup(
            point_de_vie1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        point_de_vie1Layout.setVerticalGroup(
            point_de_vie1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        JaugePoint_de_vie.add(point_de_vie1);

        javax.swing.GroupLayout point_de_vie2Layout = new javax.swing.GroupLayout(point_de_vie2);
        point_de_vie2.setLayout(point_de_vie2Layout);
        point_de_vie2Layout.setHorizontalGroup(
            point_de_vie2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        point_de_vie2Layout.setVerticalGroup(
            point_de_vie2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        JaugePoint_de_vie.add(point_de_vie2);

        javax.swing.GroupLayout point_de_vie4Layout = new javax.swing.GroupLayout(point_de_vie4);
        point_de_vie4.setLayout(point_de_vie4Layout);
        point_de_vie4Layout.setHorizontalGroup(
            point_de_vie4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        point_de_vie4Layout.setVerticalGroup(
            point_de_vie4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        JaugePoint_de_vie.add(point_de_vie4);

        javax.swing.GroupLayout point_de_vie6Layout = new javax.swing.GroupLayout(point_de_vie6);
        point_de_vie6.setLayout(point_de_vie6Layout);
        point_de_vie6Layout.setHorizontalGroup(
            point_de_vie6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        point_de_vie6Layout.setVerticalGroup(
            point_de_vie6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        JaugePoint_de_vie.add(point_de_vie6);

        javax.swing.GroupLayout point_de_vie10Layout = new javax.swing.GroupLayout(point_de_vie10);
        point_de_vie10.setLayout(point_de_vie10Layout);
        point_de_vie10Layout.setHorizontalGroup(
            point_de_vie10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        point_de_vie10Layout.setVerticalGroup(
            point_de_vie10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        JaugePoint_de_vie.add(point_de_vie10);

        add(JaugePoint_de_vie, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 30, 150));

        javax.swing.GroupLayout zone_d_interaction2Layout = new javax.swing.GroupLayout(zone_d_interaction2);
        zone_d_interaction2.setLayout(zone_d_interaction2Layout);
        zone_d_interaction2Layout.setHorizontalGroup(
            zone_d_interaction2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );
        zone_d_interaction2Layout.setVerticalGroup(
            zone_d_interaction2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        add(zone_d_interaction2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 460, 150));

        PopJ2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout PopJ2Layout = new javax.swing.GroupLayout(PopJ2);
        PopJ2.setLayout(PopJ2Layout);
        PopJ2Layout.setHorizontalGroup(
            PopJ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );
        PopJ2Layout.setVerticalGroup(
            PopJ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );

        add(PopJ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 100, -1));

        imageJ2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout imageJ2Layout = new javax.swing.GroupLayout(imageJ2);
        imageJ2.setLayout(imageJ2Layout);
        imageJ2Layout.setHorizontalGroup(
            imageJ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
        );
        imageJ2Layout.setVerticalGroup(
            imageJ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );

        add(imageJ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, -1));

        zone_d_interaction3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout zone_d_interaction5Layout = new javax.swing.GroupLayout(zone_d_interaction5);
        zone_d_interaction5.setLayout(zone_d_interaction5Layout);
        zone_d_interaction5Layout.setHorizontalGroup(
            zone_d_interaction5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        zone_d_interaction5Layout.setVerticalGroup(
            zone_d_interaction5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        zone_d_interaction3.add(zone_d_interaction5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 160));

        javax.swing.GroupLayout zone_d_interaction6Layout = new javax.swing.GroupLayout(zone_d_interaction6);
        zone_d_interaction6.setLayout(zone_d_interaction6Layout);
        zone_d_interaction6Layout.setHorizontalGroup(
            zone_d_interaction6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        zone_d_interaction6Layout.setVerticalGroup(
            zone_d_interaction6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        zone_d_interaction3.add(zone_d_interaction6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 100, 160));

        javax.swing.GroupLayout zone_d_interaction7Layout = new javax.swing.GroupLayout(zone_d_interaction7);
        zone_d_interaction7.setLayout(zone_d_interaction7Layout);
        zone_d_interaction7Layout.setHorizontalGroup(
            zone_d_interaction7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        zone_d_interaction7Layout.setVerticalGroup(
            zone_d_interaction7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        zone_d_interaction3.add(zone_d_interaction7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 100, 160));

        javax.swing.GroupLayout zone_d_interaction8Layout = new javax.swing.GroupLayout(zone_d_interaction8);
        zone_d_interaction8.setLayout(zone_d_interaction8Layout);
        zone_d_interaction8Layout.setHorizontalGroup(
            zone_d_interaction8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        zone_d_interaction8Layout.setVerticalGroup(
            zone_d_interaction8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        zone_d_interaction3.add(zone_d_interaction8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 100, 160));

        add(zone_d_interaction3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 460, 180));

        JaugePoint_de_vie1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout point_de_vie3Layout = new javax.swing.GroupLayout(point_de_vie3);
        point_de_vie3.setLayout(point_de_vie3Layout);
        point_de_vie3Layout.setHorizontalGroup(
            point_de_vie3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        point_de_vie3Layout.setVerticalGroup(
            point_de_vie3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        JaugePoint_de_vie1.add(point_de_vie3);

        javax.swing.GroupLayout point_de_vie5Layout = new javax.swing.GroupLayout(point_de_vie5);
        point_de_vie5.setLayout(point_de_vie5Layout);
        point_de_vie5Layout.setHorizontalGroup(
            point_de_vie5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        point_de_vie5Layout.setVerticalGroup(
            point_de_vie5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        JaugePoint_de_vie1.add(point_de_vie5);

        javax.swing.GroupLayout point_de_vie7Layout = new javax.swing.GroupLayout(point_de_vie7);
        point_de_vie7.setLayout(point_de_vie7Layout);
        point_de_vie7Layout.setHorizontalGroup(
            point_de_vie7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        point_de_vie7Layout.setVerticalGroup(
            point_de_vie7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        JaugePoint_de_vie1.add(point_de_vie7);

        javax.swing.GroupLayout point_de_vie8Layout = new javax.swing.GroupLayout(point_de_vie8);
        point_de_vie8.setLayout(point_de_vie8Layout);
        point_de_vie8Layout.setHorizontalGroup(
            point_de_vie8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        point_de_vie8Layout.setVerticalGroup(
            point_de_vie8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        JaugePoint_de_vie1.add(point_de_vie8);

        javax.swing.GroupLayout point_de_vie11Layout = new javax.swing.GroupLayout(point_de_vie11);
        point_de_vie11.setLayout(point_de_vie11Layout);
        point_de_vie11Layout.setHorizontalGroup(
            point_de_vie11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        point_de_vie11Layout.setVerticalGroup(
            point_de_vie11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        JaugePoint_de_vie1.add(point_de_vie11);

        add(JaugePoint_de_vie1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 30, 150));

        PopJ1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout PopJ1Layout = new javax.swing.GroupLayout(PopJ1);
        PopJ1.setLayout(PopJ1Layout);
        PopJ1Layout.setHorizontalGroup(
            PopJ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );
        PopJ1Layout.setVerticalGroup(
            PopJ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );

        add(PopJ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 100, 150));

        jLabel1.setText("Pioche");

        javax.swing.GroupLayout zone_d_interaction4Layout = new javax.swing.GroupLayout(zone_d_interaction4);
        zone_d_interaction4.setLayout(zone_d_interaction4Layout);
        zone_d_interaction4Layout.setHorizontalGroup(
            zone_d_interaction4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zone_d_interaction4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        zone_d_interaction4Layout.setVerticalGroup(
            zone_d_interaction4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zone_d_interaction4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        add(zone_d_interaction4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 130, 180));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JaugePoint_de_vie;
    private javax.swing.JPanel JaugePoint_de_vie1;
    private com.ilu4.jeuxpirate.boundary.components.ImagePanel PopJ1;
    private com.ilu4.jeuxpirate.boundary.components.ImagePanel PopJ2;
    private com.ilu4.jeuxpirate.boundary.components.ImagePanel imageJ1;
    private com.ilu4.jeuxpirate.boundary.components.ImagePanel imageJ2;
    private com.ilu4.jeuxpirate.boundary.components.JCarte jCarte1;
    private com.ilu4.jeuxpirate.boundary.components.JCarte jCarte2;
    private javax.swing.JLabel jLabel1;
    private com.ilu4.jeuxpirate.boundary.components.Point_de_vie point_de_vie1;
    private com.ilu4.jeuxpirate.boundary.components.Point_de_vie point_de_vie10;
    private com.ilu4.jeuxpirate.boundary.components.Point_de_vie point_de_vie11;
    private com.ilu4.jeuxpirate.boundary.components.Point_de_vie point_de_vie2;
    private com.ilu4.jeuxpirate.boundary.components.Point_de_vie point_de_vie3;
    private com.ilu4.jeuxpirate.boundary.components.Point_de_vie point_de_vie4;
    private com.ilu4.jeuxpirate.boundary.components.Point_de_vie point_de_vie5;
    private com.ilu4.jeuxpirate.boundary.components.Point_de_vie point_de_vie6;
    private com.ilu4.jeuxpirate.boundary.components.Point_de_vie point_de_vie7;
    private com.ilu4.jeuxpirate.boundary.components.Point_de_vie point_de_vie8;
    private com.ilu4.jeuxpirate.boundary.components.Zone_d_interaction zone_d_interaction1;
    private com.ilu4.jeuxpirate.boundary.components.Zone_d_interaction zone_d_interaction2;
    private com.ilu4.jeuxpirate.boundary.components.Zone_d_interaction zone_d_interaction3;
    private com.ilu4.jeuxpirate.boundary.components.Zone_d_interaction zone_d_interaction4;
    private com.ilu4.jeuxpirate.boundary.components.Zone_d_interaction zone_d_interaction5;
    private com.ilu4.jeuxpirate.boundary.components.Zone_d_interaction zone_d_interaction6;
    private com.ilu4.jeuxpirate.boundary.components.Zone_d_interaction zone_d_interaction7;
    private com.ilu4.jeuxpirate.boundary.components.Zone_d_interaction zone_d_interaction8;
    // End of variables declaration//GEN-END:variables

}
