/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package boundary;

/**
 *
 * @author yannf
 */
public class Plateau extends javax.swing.JPanel {

    /**
     * Creates new form Plateau
     */
    public Plateau() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelWithBackground1 = new boundary.components.JPanelWithBackground();
        point_de_vie1 = new boundary.components.Point_de_vie();

        jPanelWithBackground1.setPreferredSize(new java.awt.Dimension(720, 480));
        jPanelWithBackground1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout point_de_vie1Layout = new javax.swing.GroupLayout(point_de_vie1);
        point_de_vie1.setLayout(point_de_vie1Layout);
        point_de_vie1Layout.setHorizontalGroup(
            point_de_vie1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        point_de_vie1Layout.setVerticalGroup(
            point_de_vie1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        jPanelWithBackground1.add(point_de_vie1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelWithBackground1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelWithBackground1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private boundary.components.JPanelWithBackground jPanelWithBackground1;
    private boundary.components.Point_de_vie point_de_vie1;
    // End of variables declaration//GEN-END:variables
}
